### ISSUE TITLE
Main content has black background

### ISSUE THREAD

**Issue by knice** [ucsc/email-templates#1]
Set the HTML attribute `bgcolor="#ffffff"`in `<td>`

**Comment by ttran34** [comment]
Fixed campaign single column

**Comment by egolson** [comment]
Lotus 8.5 screenshot
![screen shot 2015-06-30 at 3 59 27 pm](https://cloud.githubusercontent.com/assets/13124595/8444008/034ff908-1f41-11e5-8259-e88751c60eac.png)

**Comment by ttran34** [comment]
Fixed 2 column background

**Comment by ttran34** [comment]
Fixed Stay Connected 2 columns

**Comment by ttran34** [comment]
Fixed Stay Connected 1 column
